import matplotlib.pyplot as plt
import pandas as pd
import random

# purpose: identify materials based on melting point
# input: melting point
# output: identify material, visualize phase diagram

# (melting point, mass)
# generated by an incinerator or some other equipment

# lead, tin, gold, copper
EXAMPLE_PAIRS = [(600.61, 15), (505.08, 45), (1337.33, 0.06), (1357.77, 25)]
EXAMPLE_PAIRS.sort()

df = pd.read_csv("pTable.csv")
METALS = dict(zip( df["melting_point"], df["name"] ))
df_prices = pd.read_csv("prices.csv", index_col=0)
PRICES = df_prices.iloc[-1].to_dict()
# print(PRICES)

def get_metal(melting_point):
    return METALS[melting_point]

def get_price(metal):
    return PRICES[metal]

def get_color(metal):
    return ( random.random(), random.random(), random.random() )

def analyze_sample(pairs):
    metals = [ get_metal(p[0]) for p in pairs ]
    total_mass = sum(p[1] for p in pairs)
    percentages = [ p[1]/total_mass for p in pairs ]
    prices = [ get_price(metal) * (1 if metal != "Gold" else 300) for metal in metals ]
    colors = ['dimgray', 'silver', 'gold', 'yellowgreen']
    
    fix, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))
    ax1.pie(percentages, labels=metals, autopct='%1.1f%%', colors=colors)
    ax1.set_title("Composition of sample")

    ax2.bar(metals, prices, color=colors)
    ax2.set_title("Prices of metals")
    plt.show()

analyze_sample(EXAMPLE_PAIRS)
